name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches: [ 'main' ]

jobs:
  deploy-storybook:
    uses: darrylmorton/ct-continuous-workflows/.github/workflows/storybook-github-pages-publish.yml@feature/storybook-deploy-workflow
    with:
      nodejs-version: '22.x'
  